### PR TITLE
fix: possible fix for the cell losing focus when clicking on the border

### LINKED ISSUE #2987: Cell loses focus when clicking on its outline
## Steps to reproduce

1. Prerequisites:
    1. On the table page click on a cell to focus it.
    1. When the cell is focused, you can use the <kbd>Up</kbd> and <kbd>Down</kbd> arrow keys to move the active cell. This is good.
    1. Click on the "Filter" button above the table to open the filtering dropdown. Click it again to close it. Now that button is focused instead of a cell, and you won't be able to use the arrow keys to move the active cell. This is okay, but important to understand.

1. Increase your browser zoom to something like 300% to make this easier.
1. Click on a cell to focus it.
1. Click on the blue cell border.
1. Expect the cell to remain focused.
1. Observe that the cell loses focus.

### PR DESCRIPTION
**Pull request by sharath-1517**
Fixes #2987

**Technical details**

- Found that the cell was given box-shadow for the ```[data-active-cell]``` element.
- I have changed the box-shadow to outline and set outline-offset in order to make sure that the outline stays inside the cell avoiding overlaps with other cells.

**Screenshots**

- Active state of the cell
Screenshot 2024-12-16 at 4 27 45 PM

- Inactive state of the cell
Screenshot 2024-12-16 at 4 27 47 PM

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I tried running the project locally and verified that there are no
  visible errors.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sharath-1517** [comment]
Thank you for the review. I'll make sure to check to check in other browsers as well the next time. @seancolsen could you list out the browsers that I need to check with for each UI change please? Thanks!

**Comment by seancolsen** [comment]
> could you list out the browsers that I need to check

Generally just only one browser, so long as it's a relatively recent one. We very rarely run into browser-specific issues, so I don't think it's worth the time to check multiple browsers regularly. I mentioned two in my comment above because I was surprised and confused at the possibility that I might be seeing something different from what you're seeing. If that does end up being the case, we can continue troubleshooting to figure out why.

**Comment by sharath-1517** [comment]
> > could you list out the browsers that I need to check
> 
> Generally just only one browser, so long as it's a relatively recent one. We very rarely run into browser-specific issues, so I don't think it's worth the time to check multiple browsers regularly. I mentioned two in my comment above because I was surprised and confused at the possibility that I might be seeing something different from what you're seeing. If that does end up being the case, we can continue troubleshooting to figure out why.

Sure Sean, I get you. I guess I'll check cross browser issues for this issue, since I saw an issue live in your dev in firefox and chromium. I'll let you know if I get to know anything or make push it so you can take a look on it.

**Comment by zackkrida** [comment]
@seancolsen I'd be curious for you to test this again. I'm seeing the correct behavior in Chrome `Version 131.0.6778.139 (Official Build) (64-bit)` and Firefox `133.0.3 (64-bit)` for Fedora.

Screenshot From 2024-12-18 10-19-32

This appears to fix the documented bug, and also has a nice benefit of fixing an older behavior where table headers covered the cell focus:

image

**Comment by sharath-1517** [comment]
> @sharath-1517 based on the code changes, which only change from using box-shadow to an offset outline for the cell border, I believe @seancolsen may have been facing a different issue or configuration problem. It's not clear to me how the code here would produce the result in his screenshot.
> 
> I'd like to have Sean take another look before you check potential issues. Thanks!

Got it, thanks!

**Comment by seancolsen** [comment]
Thanks @zackkrida. I tried again. Yeah, something must have been messed up when I first viewed this.

I tried again, and here's what I'm seeing:

image

This seems consistent with the screenshots in the PR description, so I'll continue my review from here...

This is still not okay because it modifies the visual design of the active cell indicator. I have exactly the same feedback here as [the feedback I left on a previous PR](https://github.com/mathesar-foundation/mathesar/pull/3185#pullrequestreview-1617630542) attempting to tackle this same issue. The indicator needs to extend outside the active cell.

Consider some sort of `pointer-events: none;` CSS or something. I've not dug into it myself, but I don't imagine it would be that tricky. Perhaps it is though. But that's what we're after: no visual changes. Just changes in click behavior.

**Comment by sharath-1517** [comment]
> Thanks @zackkrida. I tried again. Yeah, something must have been messed up when I first viewed this.
> 
> I tried again, and here's what I'm seeing:
> 
> image
> 
> This seems consistent with the screenshots in the PR description, so I'll continue my review from here...
> 
> This is still not okay because it modifies the visual design of the active cell indicator. I have exactly the same feedback here as [the feedback I left on a previous PR](https://github.com/mathesar-foundation/mathesar/pull/3185#pullrequestreview-1617630542) attempting to tackle this same issue. The indicator needs to extend outside the active cell.
> 
> Consider some sort of `pointer-events: none;` CSS or something. I've not dug into it myself, but I don't imagine it would be that tricky. Perhaps it is though. But that's what we're after: no visual changes. Just changes in click behavior.

Hey Sean yes of course I read the previous PR conversation just right after I created this PR. I will make sure to make some research on it and fix it up if that's alright? Also could you assign me this issue? Thanks!

**Comment by sharath-1517** [comment]
@seancolsen seems like you've already assigned me, please kindly ignore that question from previous comment. Thanks for your patience.

**Comment by sharath-1517** [comment]
I am closing this PR since I couldn't find any leads on this issue. If I get to know anything that could be used to fix this issue I'll create a new PR.

**Pull request closed without merging**
