### PR TITLE
Fix incorrectly placed filtering dropdown

### LINKED ISSUE #3397: Incorrectly placed filtering dropdown causes layout overflow on record page
## Steps to reproduce

1. Navigate to a record page with linked records

1. Within the table widget, open the filtering dropdown and proceed to add a filter.

1. Expect to see the filtering dropdown positioned below the filter button and with its right edge aligned with the right of the rest of the content already on the page

1. Instead observe that it causes this weird layout problem

image

I found this issue during QA of the v0.1.4 release but I was able to reproduce it on the demo site so I'm putting it in the Backlog milestone.

### PR DESCRIPTION
**Pull request by shardulgawande27**
Fixes #3397

Title : Fix - Incorrectly placed filtering dropdown causes layout overflow on record page

Desc : This pull request fixes #3397 

**Technical details**

Made style changes in: 
1. FilterEntry.svelte
2. Dropdown.scss
3. InputGroup.scss

**Screenshots**

298380511-9b43ca13-5f38-4720-ba11-ca87ba1d5403

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by seancolsen — CHANGES_REQUESTED** [review]
I'm still reproducing the bug after trying with your changes

image

Also:

- I pushed a commit which reverts changes made to package-lock.json — don't commit changes to that file.
- I wouldn't imagine that this fix requires a ton of CSS change. My hunch is that there is an issue with the placement logic used by our popper library or our specific usage of that library here. Or there could be a _small_ CSS issue causing that placement to go haywire.

You're welcome to continue working on this if you like, but my high-level feedback is that this doesn't appear to be going in the right direction. I'll close the PR on or after 2024-02-18 if we haven't heard any updates by then.

**Comment by shardulgawande27** [comment]
Sure @seancolsen I will continue to work on this issue and thank you for your feedback Sean. I will try my best to take this in the correct direction and keep in mind the points you mentioned.

**Comment by seancolsen** [comment]
@shardulgawande27 are you still working on this? If we don't hear from you by 2024-03-15 we may choose to close this PR.

**Comment by shardulgawande27** [comment]
Hi @seancolsen i apologise for the inconvenience , been really busy with work since last month,but i will work on this issue this week for sure.

**Comment by seancolsen** [comment]
@shardulgawande27 just checking in again... when do you plan on continuing work on this? Please know that there's no pressure from our end. It's fine if you want to close this. I just need to keep our PR queue somewhat fresh, so I'll need to close this myself if you are no longer going to work on it.

**Comment by seancolsen** [comment]
@shardulgawande27 This seems stale at this point so I'm closing it.

**Pull request closed without merging**
