### PR TITLE
Update Installation Documentation for Release 0.1.4

### LINKED ISSUE #3166: Reframe docker compose installation
~~Based on our [installation plan](https://wiki.mathesar.org/en/projects/installation-improvements-plan-0_1_4), we won't be using supporting docker-compose installation. we should be deprecating it for now until we have a migration plan for the existing users who installed Mathesar using docker-compose~~

~~The following guides need to be marked as deprecated~~
- ~~[Docker compose installation](https://docs.mathesar.org/installation/docker-compose/)~~
- ~~["customizing docker compose" page](https://docs.mathesar.org/configuration/customize-docker-compose/)~~

### According to the new plan:
- Docker compose file and its self documenting nature should serve as a baseline for people looking at alternate but quite similar installation methods like k8s, docker swarm, etc. 
- Docs on docs.mathesar.org should be minimal and should refer to the docker compose file for details.

## Additional context
~~Blocked by #3072~~

### LINKED ISSUE #3167: Remove guided installation section
Based on our [installation plan](https://wiki.mathesar.org/en/projects/installation-improvements-plan-0_1_4), we won't be using the guided script anymore as a recommended installation method. 

- [Guided script page contents](https://docs.mathesar.org/installation/guided-install/) has to be removed from the installation documentation 
- The [Guided script page contents](https://docs.mathesar.org/installation/guided-install/) should point to [deprecated docker-compose](https://docs.mathesar.org/installation/docker-compose/) administration commands for users who are already installed Mathesar using the guided install

**Additional Context**

Blocked by #3166

### LINKED ISSUE #3169: Deprecate Build from scratch documentation
Based on our [installation plan](https://wiki.mathesar.org/en/projects/installation-improvements-plan-0_1_4), we won't be supporting Install from scratch as a recommended installation method. 

The following guides need to be marked as deprecated
- [Build from scratch](https://docs.mathesar.org/installation/build-from-source/) 
- The [Build from scratch](https://docs.mathesar.org/installation/guided-install/) should point to the Debian install documentation added by #3165 for users who have already installed Mathesar using the "Build from scratch" instructions

### LINKED ISSUE #3378: Update docs with regard to MATHESAR_DATABASES
- Make sure that our instructions for upgrading to v0.1.4 instruct Mathesar administrators to delete `MATHESAR_DATABASES` from their environment variables after upgrading.
- Make sure that (aside from the point above), we don't mention `MATHESAR_DATABASES` in the docs.

## Additional context

- Discussed in #3344

### LINKED ISSUE #3404: Update process for docker compose is wrong
## Description

Currently, the update process for a docker compose installation doesn't work as documented. If you try to upgrade from 0.1.3 to 0.1.4, your installation will cease to recognize its Django database under some (most) cases, causing distress. No data is lost, but manual intervention is required in order to reattach the service to the Django DB. This is because the `DJANGO_DATABASE_URL` is no longer supported by the new setup.

## Expected behavior

Either we need to improve the environment variable handling and deprecate rather than remove `DJANGO_DATABASE_URL`, or we need to document how a user can update their `.env` file and `docker-compose.yml` file to match with the new variables.

I prefer the former solution, on the off chance we have users who have customized  their docker compose files and don't want to change them. It's also more well-aligned with the goal of the docker compose installation style (i.e., that the user _should_ customize or write their own docker compose configuration)

## To Reproduce

Try to upgrade from 0.1.3 to 0.1.4 with non-default Django DB

## Additional context

Discovered while updating the internal.mathesar.org server. Introduced by one of the last merged PRs to the branch before the release was cut (so it went unnoticed).

### PR DESCRIPTION
**Pull request by silentninja**
Fixes #3166
Fixes #3169
Fixes #3167 
Fixes #3378
Fixes #3404

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kgodey** [comment]
Sorry I accidentally clicked the wrong button and I'm not sure how to mark as draft again (I'm on GitHub mobile).

**Comment by kgodey** [comment]
Okay, on my computer now and converted back to draft.

**Comment by mathemancer** [comment]
@silentninja I'll take this over; thanks for getting it started.

**Comment by mathemancer** [comment]
@Anish9901 I'm going to have to remove the `bash` highlighting. It's defective.

**Comment by mathemancer** [comment]
@kgodey I think we should remove the guided script entirely, rather than deprecating it. I don't even know what deprecating would mean in this context. Is that okay with you?

**Comment by kgodey** [comment]
@mathemancer I'm fine with removing entirely.

**Comment by mathemancer** [comment]
@kgodey Related to #3277 : with our new setup (in particular, without the guided script installation), I see no reason to recommend `sudo` for any command. E.g., if you copy-and-paste a docker command into your console, and it doesn't work without `sudo`, your console will tell you that, and anyone who uses a console regularly will just reflexively type `sudo !!` . I'd also, however, argue that this holds true for any of the commands we give (e.g., in the build from scratch instructions). For consistency, I think we should either prepend all such commands with `sudo`, or none of them. After pondering, I'm inclined to go with the latter option. Do you have an opinion on that?

**Comment by seancolsen** [comment]
@mathemancer

> I see no reason to recommend sudo for any command

I want to push back on this a bit.

You said: 

> anyone who uses a console regularly will just reflexively type `sudo !!`

I don't think this is necessarily true. I've been using the console regularly for 20 years but did not understand these finicky things about Docker until I started working on Mathesar. If I were following some docs that told me to run a docker command without sudo, I'd try it and then I'd see this:

> permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json": dial unix /var/run/docker.sock: connect: permission denied

At that point I would genuinely be confused. Perhaps I would _try_ prepending that command with `sudo` as a troubleshooting measure, but I don't think I'd necessarily reach for that first unless I already had an understanding about how Docker works on Linux. In general I'm wary of running anything with sudo unless I really understand what's going on. If we're making an effort to prioritize ease of installation, I don't think we should assume that all Mathesar administrators will have this level of understanding about Docker — and even about sudo itself. Given that we've identified installation as a major weak point, I think it's worth preserving this extra hand-holding in our docs.

However, I don't think we necessarily need to have sudo/non-sudo options littered throughout all the docs steps (as we currently do in areas). But I do think it's a large enough point of friction to warrant at least one mention, perhaps within an admonition box.

**Comment by mathemancer** [comment]
> @mathemancer
> 
> > I see no reason to recommend sudo for any command
> 
> I want to push back on this a bit.
> 
> You said:
> 
> > anyone who uses a console regularly will just reflexively type `sudo !!`
> 
> I don't think this is necessarily true. I've been using the console regularly for 20 years but did not understand these finicky things about Docker until I started working on Mathesar. If I were following some docs that told me to run a docker command without sudo, I'd try it and then I'd see this:
> 
> > permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json": dial unix /var/run/docker.sock: connect: permission denied
> 
> At that point I would genuinely be confused. Perhaps I would _try_ prepending that command with `sudo` as a troubleshooting measure, but I don't think I'd necessarily reach for that first unless I already had an understanding about how Docker works on Linux. In general I'm wary of running anything with sudo unless I really understand what's going on. If we're making an effort to prioritize ease of installation, I don't think we should assume that all Mathesar administrators will have this level of understanding about Docker — and even about sudo itself. Given that we've identified installation as a major weak point, I think it's worth preserving this extra hand-holding in our docs.
> 
> However, I don't think we necessarily need to have sudo/non-sudo options littered throughout all the docs steps (as we currently do in areas). But I do think it's a large enough point of friction to warrant at least one mention, perhaps within an admonition box.

Maybe once per page where relevant commands appear? I'll put together that version and we can discuss from there.

**Comment by mathemancer** [comment]
@seancolsen What do you think of the `sudo` related copy in [this commit](https://github.com/mathesar-foundation/mathesar/pull/3324/commits/5a961ab0726fd1394b4dd622aa97b2c81542a37c)?

**Comment by seancolsen** [comment]
@mathemancer 

> once per page where relevant commands appear

Agreed.

> the `sudo` related copy in [this commit](https://github.com/mathesar-foundation/mathesar/pull/3324/commits/5a961ab0726fd1394b4dd622aa97b2c81542a37c)

Looks good.

**Comment by seancolsen** [comment]
I splintered the conceptual overview content out of this PR so that we can get it merged more quicker. I don't think that content even needs to block the v0.1.4 release. We can continue that work in #3394.

**Comment by kgodey** [comment]
What is left to do to get this merged?

**Comment by seancolsen** [comment]
Good question @kgodey.

There are still some lose ends to tie up and `TODO` items in the content. I also have some additional changes locally which require some conversation with Brent to finish. I'd really like to have a pairing session with Brent on this, and I've reached out to him to schedule one. My recent lack of availability has made this tough.

**Comment by seancolsen** [comment]
This PR now contains the 0.1.4 release notes at `docs/docs/releases/0.1.4.md`

@mathemancer I need you to fill in places that say `__TODO_BRENT__`

@Anish9901 I need you to fill in places that say `__TODO_ANISH__`

I've assigned you both. Please push commits to resolve these TODO items.

**Pull request merged**
