### PR TITLE
Cleanup django migrations

### LINKED ISSUE #3296: Clean up django migrations before 0.1.4 release
## Description
The current [django migration scripts in develop](https://github.com/centerofci/mathesar/tree/develop/mathesar/migrations) are messy:

```
- 0001_initial.py
- 0002_datafile_type.py
- 0003_datafile_max_level.py
- 0004_shares.py
- 0005_datafile_sheet_name.py
- 0005_user_display_language.py
- 0006_auto_20230906_0413.py
- 0007_auto_20230913_1912.py
- 0008_auto_20230921_1834.py
- 0009_merge_20231025_1733.py
```

Many of them are not descriptive, there's 2 with the same number (0005) and one script (0009) to make sure the second one is included. We ought to clean this up.

The [previous release `0.1.3`](https://github.com/centerofci/mathesar/tree/0.1.3/mathesar/migrations) went with `0004_shares.py`. Migrations after that needs to be merged and simplified before the next release `0.1.4`.

## Additional context
- [Matrix conversation on the Backend channel](https://matrix.to/#/!UZILDSNKobkelUYwBp:matrix.mathesar.org/$gOhqujyyxgoGvOLjixLJotMILTmdC8DnJ-CBOvPwoDQ?via=matrix.mathesar.org&via=matrix.org)

## Status

- ~~Blocked on merging of #3177 (because that PR introduces migrations)~~

### PR DESCRIPTION
**Pull request by pavish**
Fixes #3296 

**Technical details**
* Cleans up and merges migrations from 0005 into a single file.
* Moves custom logic to support SQLite present in [0007_auto_20230913_1912.py](https://github.com/mathesar-foundation/mathesar/compare/cleanup_migration_scripts?expand=1#diff-009bc420f51118b05f9538b01870313d3790807f690f94de00090d6c5085fae6) to a RunPython function call.

**Note**
* Developers (and users using develop branch) would have to reset their mathesar_django DB once this PR is merged.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kgodey** [comment]
> Developers (and users using develop branch) would have to reset their DB once this PR is merged.

How are we handling this for the release? We don't expect people to reset their DBs, right?

**Comment by pavish** [comment]
@kgodey 

> How are we handling this for the release? We don't expect people to reset their DBs, right?

No, anyone upgrading from 0.1.3 **will not have to** reset their DBs.

Only those using the `develop` branch will have to reset their DBs (or atleast manually reset the migration state within Django).

**Comment by pavish** [comment]
Marking as draft to debug test failures

**Review by mathemancer — APPROVED** [review]
Okay, I checked that everything works smoothly upgrading from 0.1.3 (it does), and starting fresh (also fine).

This  is nice; thanks, @pavish !

I'm approving, but leaving it to you to send the prerequisite emails and messages before merging.

**Comment by pavish** [comment]
[This email](https://groups.google.com/a/mathesar.org/g/mathesar-developers/c/AgoDBehkilA/m/qwb86fcmAAAJ) to mathesasr-developers group contains instructions to follow once the PR is merged.

**Pull request merged**
