### PR TITLE
[i18n] Export & import translations

### PR DESCRIPTION
**Pull request by rajatvijay**
Relates #2927 

**Pre-requisites**

It needs GNU's `gettext` to be installed in the docker

```
docker exec -it mathesar_service_dev /bin/bash
apt update
apt install gettext
```
_I will add this to the documentation once I get to the documentation tasks listed [here](https://github.com/centerofci/mathesar/issues/2927)._ 

**Uploading BE translations to transifex**

```
docker exec -it mathesar_service_dev /bin/bash
./generate-and-push-be-translations.sh
```

**Downloading BE translations from transifex**

```
docker exec -it mathesar_service_dev /bin/bash
./pull-and-import-be-translations.sh
```

**Uploading FE translations to transifex**

```
docker exec -it mathesar_service_dev /bin/bash
cd mathesar_ui
npm run i18n:upload-source-strings
```

**Downloading FE translations from transifex**

```
docker exec -it mathesar_service_dev /bin/bash
cd mathesar_ui
npm run i18n:download-translations
```

**Env token**

These scripts need `TRANSIFEX_TOKEN` to be able to authenticate with the transifex service and identify `mathesar` project.
The scripts are written in a way that if the `TRANSIFEX_TOKEN` is not available in the environment it prompts the user. 

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by seancolsen** [comment]
@rajatvijay I've skimmed the diff but I'm not really sure how to review this. Can you provide some more instruction for me? What do I do to test this out? What should I expect to happen if it works?

This is the sort of PR that I think would be ideal to make in tandem with developer documentation that explains how it all works. Can we get started on that documentation now? It doesn't need to be perfect, but it's the sort of thing that will help me and Mukesh review this PR. And in running through the documentation while reviewing the PR, we'd also be stress-testing the documentation at the same time (which I think works better than trying to do it later, on its own, once someone like me already understands the whole process).

**Comment by silentninja** [comment]
> This is the sort of PR that I think would be ideal to make in tandem with developer documentation that explains how it all works

Agreed. I am not sure what is meant by "Uploading BE translations to transifex", I assume it is for uploading the string to be translated. It will be good to understand the translation process before the PR is reviewed

**Comment by rajatvijay** [comment]
@seancolsen @silentninja Added the translations required for review.

**Comment by seancolsen** [comment]
@pavish said he would take this off my plate today, so I'm re-assigning it.

**Review by pavish — CHANGES_REQUESTED** [review]
@rajatvijay This PR is stacked on top of https://github.com/centerofci/mathesar/pull/3104, which is again stacked on another PR https://github.com/centerofci/mathesar/pull/3103 which has a number of conflicts.

Also, I think it would be better to have the following before reviewing the PR:
1. Most of the code in this PR is NodeJS and not frontend code. I'd like them to be present in an entirely separate directory instead of the the frontend source code (i.e. outside of `/src`).
1. Add the dependencies (`gettext`) to the docker image (or atleast add commands to the dev docker compose setup), instead of having to do it manually.
1. Provide the dev documentation for the entire process, as both @seancolsen and @silentninja have pointed out.

I'm marking this PR as a draft until all these are addressed.

**Comment by seancolsen** [comment]
Assigning to @pavish to finish the remaining work here

**Comment by pavish** [comment]
Closing this PR as this is superseded by https://github.com/mathesar-foundation/mathesar/pull/3321

**Pull request closed without merging**
