### PR TITLE
Records grouping bugfix

### LINKED ISSUE #3742: Front end can't match groups with records
Previously, when grouping records using the REST API, each group object returned had a `result_indices` field. The front end relied on this field to match groups up with their corresponding result records.

The RPC-based records grouping added in #3721 doesn't seem to provide any way for the front end to match groups to their records.

To minimize implementation time, ideally, we'd use the same structure — a `result_indices` (array of numbers) within each group object.

I can see that the new RPC API _does_ provide a `results_eq`, but that doesn't fully allow the front end to match groups with records. For example if I'm grouping an email column by email domain, then `results_eq` will show only the domain, and the front end won't be able to know what the domain is for the emails within each record.

### PR DESCRIPTION
**Pull request by mathemancer**
Fixes #3742 

This adds a new field to the `grouping` response to collect result indices.

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the `develop` branch of the repository
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [X] I added tests for the changes I made (if applicable).
- [X] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by mathemancer** [comment]
@Anish9901 This PR is dependent on #3749 , and shouldn't be merged until after that one. But, it's ready for review.

**Comment by mathemancer** [comment]
@seancolsen This is probably worth a quick glance for behavior if you have time.

**Review by Anish9901 — APPROVED** [review]
Looks good to me!

**Review by seancolsen — CHANGES_REQUESTED** [review]
Structurally, this is good.

However, as far as I can tell, the `result_indices` was using zero-based indexing in the REST API and now is using 1-based indexing in this PR.

From an API consumer's perspective, I think 0-based indexing would be more intuitive. And it's also how the front end already expects this data to be formed. Do you think you could change it to be 0-based?

**Comment by mathemancer** [comment]
> Structurally, this is good.
> 
> However, as far as I can tell, the `result_indices` was using zero-based indexing in the REST API and now is using 1-based indexing in this PR.
> 
> From an API consumer's perspective, I think 0-based indexing would be more intuitive. And it's also how the front end already expects this data to be formed. Do you think you could change it to be 0-based?

Hmmmmmm. I took that to be primary key values. So, that's what we're returning.

**Comment by mathemancer** [comment]
Okay, I made the change. Should be the same as the old way now.

**Comment by seancolsen** [comment]
Corresponding front end PR: #3755

**Pull request merged**
