### PR TITLE
Add multiple stages to Dockerfile, remove NodeJS & unnecessary source files from production image

### PR DESCRIPTION
**Pull request by pavish**
**Technical details**
* This PR separates base, development, and production stages on the Dockerfile.
* Installs Node and builds the frontend files on the development stage.
* The production stage copies the built static files from the development stage, and does not contain node.
* The production stage also removes unnecessary source files.
* The argument `PYTHON_REQUIREMENTS` is removed and each stage specifies the requirements file it uses.
* Entrypoints are now directly mentioned on each stage instead of being specified on the compose files.

**New image sizes**
|                | Latest release image (0.1.5) | This PR (2024-03-05) | Size decreased | % size decrease |
|----------------|----------------------|----------------------|----------------|-----------------|
| arm image | 851.9 MB             | 608.46 MB            | 243.44 MB      | 28.5761%        |
| amd image | 868.55 MB            | 623.86 MB            | 244.69 MB      | 28.1722%        |

Refer [mathesar-prod:2024-03-05 image on DockerHub](https://hub.docker.com/layers/mathesar/mathesar-prod/2024-03-05/images/sha256-57fa3d535974959140d88d43e859176203a96415aa98808fd1619dd9fa165eee?context=repo).

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kgodey** [comment]
Quick note that we should update the docs (if needed) before merging this in so we don't have a state where the docs are contradicting the infrastructure.

**Review by mathemancer — APPROVED** [review]
Overall, this looks great. After our talk, I also agree with this direction.

@kgodey Wouldn't the documentation just be the prod build process in the wiki? I guess we could also document how to build a prod or dev image in this repo's wiki (e.g., for local testing of a prod image, or for the internal.mathesar.org deployment) .

**Comment by kgodey** [comment]
@mathemancer I wasn't sure about the scope of this PR, I didn't know if e.g. we needed to remove NodeJS steps from the build from scratch page. My comment was meant as a reminder to ensure docs were changed if needed, I wasn't suggesting any specific changes.

**Comment by pavish** [comment]
@kgodey The documentation change required for this PR is a one line change in the internal release instructions on our wiki. I will create a separate PR for it on that repo.

> e.g. we needed to remove NodeJS steps from the build from scratch page

This PR only targets removing NodeJS from our Docker image. I will raise a separate PR for the Install from scratch setup and make appropriate changes to the docs there.

**Comment by pavish** [comment]
Wiki updated in this commit: https://github.com/mathesar-foundation/mathesar-wiki/commit/91efcdd422e60cf8c41cad4a56465878898b28e3

**Pull request merged**
