### PR TITLE
GH workflow to create draft release with built static files

### LINKED ISSUE #2871: Allow people to install Mathesar from source without NodeJS
## Current behavior

- Our docs [require](https://github.com/centerofci/mathesar/blob/develop/docs/docs/installation/build-from-source/index.md?plain=1#L8L11) NodeJS to install Mathesar from source.

- We don't actually need Node to _run_ Mathesar though.

- This installation requirement might present unnecessary friction for people wishing to install Mathesar.

## Desired behavior

- Our release process should include a build step to produces a tarball that people can download. Then they would be able to install Mathesar without NodeJS.

CC @pavish @silentninja

### PR DESCRIPTION
**Pull request by pavish**
Fixes #2871 

**Details**
* Adds a workflow that creates a draft release whenever a tag is pushed. This draft release includes the built frontend static files.
  * Tested this on [my fork](https://github.com/pavish/mathesar/releases), since this needs to be on the develop branch inorder for us to test it.
* Updates docs:
  * Removes NodeJS & npm dependencies and downloads & extracts static_files to correct location
  * Adds step to compile the Django translation files (This seems to have been missed previously, I only caught it when adding ja translations).

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by pavish** [comment]
@Anish9901

> instead of creating a draft release it creates and uploads static assets once a release is created/edited.

The current plan is to automate creating a draft release with the frontend static assets when a tag is created, when a release branch is cut. Refer [this mail thread](https://groups.google.com/a/mathesar.org/g/mathesar-developers/c/xpo3Ui1NkNU/m/2r2Fa-FyAQAJ).

**Comment by pavish** [comment]
This introduces changes to our release process. I will raise a separate PR for it on the wiki repo.

**Comment by seancolsen** [comment]
@pavish I'm a little confused about the workflow here. You said:

> This introduces changes to our release process. I will raise a separate PR for it on the wiki repo.

I think that once I read _that_ PR I'll either be satisfied or I'll have some more specific questions to ask. So I'm going to hold off on reviewing this until I can read the wiki PR in conjunction.

**Comment by Anish9901** [comment]
I don't see any releases on the fork you linked @pavish, I think it'd be helpful if you could link the asset in this PR.

**Comment by pavish** [comment]
@Anish9901 Draft releases aren't visible. I published it, here's how it looks: https://github.com/pavish/mathesar/releases/tag/0.1.6

**Comment by pavish** [comment]
> I think that once I read that PR I'll either be satisfied or I'll have some more specific questions to ask. So I'm going to hold off on reviewing this until I can read the wiki PR in conjunction

@seancolsen The wiki PR is here: https://github.com/mathesar-foundation/mathesar-wiki/pull/109

**Review by Anish9901 — APPROVED** [review]
Looks good to me!

**Review by seancolsen — APPROVED** [review]

**Pull request merged**
