### PR TITLE
Fix bug while deleting the database connection

### LINKED ISSUE #3361: Bugs while deleting database connection
## Description

Part 1:
- Deleting a database connection always drops associated mathesar schemas, regardless of the query_param `del_msar_schemas` being set to true or false.

Part 2:
- Deleting a database connection  with `del_msar_schemas=true` whose database is deleted outside of mathesar results in a Internal server error.   

## Expected behavior

Part 1:
- Backend should respect the query_param `del_msar_schemas`.

Part 2:
- Raise correct exception instead of an Internal server error.

## To Reproduce

Part 1:
- Try deleting a connection with and without checking the `Delete associated Mathesar schemas` box through the UI notice that `msar, __msar, and mathesar_types` gets droped regardless.

Part 2:
- Delete the database for which a connection exists using psql `drop database my_mathesar with (force);`
- Try deleting the connection from the UI with `Delete associated Mathesar schemas` checked.

### PR DESCRIPTION
**Pull request by Taherpatrawala**
Related to #3361 

When we get a `del_msar_schema` from the client side we get a string value  "true"/"false" hence the condition to check this variable always considers it to be true and deletes the database connection, so I made another check further to check the string value.
I am unsure whether I should change the exception after hearing from @mathemancer 

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by Anish9901** [comment]
Good work so far @Taherpatrawala! I've updated the expected behavior for part 2 of the issue factoring in @mathemancer's comment about the error behavior, please take a look.

**Comment by Anish9901** [comment]
@Taherpatrawala issue #3361 is a high priority for us, could you make the required changes within a couple of days?

**Comment by Taherpatrawala** [comment]
@Anish9901 On it! Should I create a separate exception in database_exceptions/exceptions.py ?

**Review by Anish9901 — APPROVED** [review]
@Taherpatrawala We've decided to handle Part 2 of the issue in a subsequent PR, your implementation of Part 1 of the issue looks good, and I've added a test in https://github.com/mathesar-foundation/mathesar/pull/3377/commits/4b138eb63e166860d47ce8055049b6869ceb7869 to ensure that it works as intended.

Thanks for your contribution!

**Pull request merged**
