### PR TITLE
Records delete bugfix

### LINKED ISSUE #3752: Modify `records.delete` RPC method to permit deleting records via stringified primary key values
From a table with a numeric primary key column, I can delete records via an RPC request like this:

```json5
{
  "jsonrpc": "2.0",
  "method": "records.delete",
  "id": 0,
  "params": {
    "database_id": 1,
    "table_oid": 692359,
    "record_ids":[
      1
    ]
  }
}
```

But, with the REST API, the front end has actually been sending _stringified_ primary key values. So it would be easier if I could send this:

```json5
{
  "jsonrpc": "2.0",
  "method": "records.delete",
  "id": 0,
  "params": {
    "database_id": 1,
    "table_oid": 692359,
    "record_ids":[
      "1"
    ]
  }
}
```

Initially, I thought: _"hmmm, sending pk values in the correct type would be more idiomatic, so why not change this on the front end?"_ But unfortunately this doesn't appear to be an easy change to make. It's possible of course. But it's hard to tell how much time. I spent 30 minutes and just ended up uncovering a bunch of problems fanning out across different modules.

So if this would be easier to change on the backend, I'd rather do that.

### PR DESCRIPTION
**Pull request by mathemancer**
Fixes #3752 

This PR lets the caller submit record IDs to be deleted in any type, and then coerces them to text (along with the actual primary key column) before comparing in the `DELETE`'s `WHERE` clause.

**Technical details**

A side-effect of this PR is that we can no longer support some more exotic primary key column types (e.g., composite types, array types), whereas the previous version would have.

We consider this to be a reasonable compromise at the moment, since we don't really officially support tables with non-integer primary keys anyway. However, because the new behavior is a bit inconsistent (and may be confusing), we should readdress this at some point, and try to come up with a better solution.

Note that we do _not_ coerce the submitted keys to the type of the primary key column, since that conversion could be lossy, and result in deleting more records than intended.

When submitting primary keys to which we apply custom formatting (e.g., datetime types), they should be formatted when submitted.

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the `develop` branch of the repository
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [X] I added tests for the changes I made (if applicable).
- [X] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by mathemancer** [comment]
@Anish9901 This shouldn't be merged until after #3751 .

**Comment by seancolsen** [comment]
Front end counterpart: #3757

**Review by seancolsen — APPROVED** [review]
Works for me!

**Comment by seancolsen** [comment]
Even though @Anish9901 hasn't yet reviewed, I'm merging this because I have a bunch of other work that I'd like to stack on top of it so that it's easier for Pavish to review while I'm gone.

If we need to make changes later, I figure we can do those in a follow-up PR.

**Pull request merged**
