### PR TITLE
Persist visibility of table inspector sections

### LINKED ISSUE #2379: Persist visibility of table inspector and its sections within localStorage
## Current behavior

- The table inspector is enabled when loading a page. Users can hide it, but it always re-appears when reloading.

- The sections within the table inspector work in a similar manner, though some are set to hidden by default.

## Desired behavior

- The visibility of the table inspector and each of its sections is synchronized with localStorage.

- We'll need to figure out a proper schema for storing this data in localStorage, taking into account the likelihood of eventually putting more data in localStorage and possibly needing to migrate existing localStorage data.

This is marked as restricted because we're not yet persisting anything to localStorage and I want to make sure this we set this up in a manner that provides a clean integration with our Svelte stores.

### PR DESCRIPTION
**Pull request by seancolsen**
Fixes #2379

This PR makes it so that the toggled visibility of the table inspector and most sections inside it are persisted in localStorage. If you hide the table inspector, it will remain hidden until you open it again — even after you close your browser tab. The same is true for all the sections in the "Table" and "Column" tab. Since there's only one section in the "Record" tab, I didn't bother persisting that, but we could add that later by following the same patterns here.

I opened this PR now because I was doing a lot of work in the table inspector for the record summary stuff, and this actually just made my development process easier. I think it will benefit users too.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by seancolsen** [comment]
@pavish I've assigned you to review from a code/implementation perspective.

@ghislaineguerin I've assigned you to review from a UX/product perspective to make sure that this is something we want.

**Review by ghislaineguerin — APPROVED** [review]
The proposed UX makes sense. We should store the user's visibility preferences.

**Review by pavish — APPROVED** [review]
Looks good to me

**Comment by zackkrida** [comment]
I was about to make a feature request but then was pleased to find this on the `develop` branch. Excellent!

**Pull request merged**
