### PR TITLE
Fix active cell displaying above row header cell

### LINKED ISSUE #3380: Active/Focused Cell is displayed over the Row Number Cell
### Unexpected Cell UI Behavior

Once you scroll enough that an active/focused cell overlaps with the row number cell at the left of the page, the active/focused cell is displayed over the Row Number cell as you continue scrolling right.

## Expected behavior

The Row number cell should be displayed above the active/focused cell.

## To Reproduce
- Zoom up to 200% or add enough columns for the horizontal scrollbar to appear.
- Select any cell.
- Scroll left until the cell reaches extreme left.
- Find it being displayed above the Row Number cell.

## Environment
Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0

## Screenshots
image

## Proposed Solution

Change the z-index in Sheet.svelte
```
--z-index__sheet__top-left-cell: 5;
```
image

### PR DESCRIPTION
**Pull request by catfo435**
Fixes #3380

Fixes the issue by changing the z-index value of the top-left-cell from 3 to 5.

## Checklist
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `develop` branch of the repository
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by seancolsen** [comment]
@catfo435, I just wanted you to know that I'm still planning to review this PR but that work is queued behind several higher priority tasks at the moment. I can't promise when I'll be able to review this, but I'll definitely get to it.

**Comment by seancolsen** [comment]
Note to self for review: PR #3393 coincidentally proposed exactly this same fix.

**Review by seancolsen — APPROVED** [review]
Thanks @catfo435

**Comment by catfo435** [comment]
No problem! @seancolsen

**Pull request merged**
