### PR TITLE
Allow unsetting schema comment using NULL

### LINKED ISSUE #3638: Unable to remove a comment on a schema
## TODO
Refactor `comment_on_schema` SQL functions to remove the comment on a schema if the comment is NULL instead of returning NULL.

### PR DESCRIPTION
**Pull request by Anish9901**
Fixes #3638

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by seancolsen — COMMENTED** [review]
As far as the behavior of `msar.set_schema_description` is concerned, I'm fine with this change.

However, I think this new approach would make `msar.patch_schema` function more like a "replace" rather than a "patch". For example, if I pass a `patch` argument like this...

```json
{ "name": "my new schema name" }
```

...then I would not expect any changes to be made to the description. But with this PR, the description would be removed. Right? That makes _patching_ a schema work more like _replacing_ a schema (in terms of the [standard verbs](https://wiki.mathesar.org/projects/2024/architecture-transition/rpc/#standard-verbs) we agreed on). Perhaps I should have written another test case to assert that patching can be performed partially.

I think it would help avoid bugs in the future if this PR could also modify `msar.patch_schema` so that it only updates the description if the description key exists in the patch.

Whether or not you choose to make that suggested change, it would also be good to update the code comment on `msar.patch_schema`, so as to clarify the new behavior of that function.

**Comment by Anish9901** [comment]
I've made your suggested change in a2529ce @seancolsen.

**Review by seancolsen — APPROVED** [review]
I've only just skimmed the diff, but yeah @Anish9901 that looks good.

**Review by mathemancer — APPROVED** [review]
Code looks fine. If the FE is okay with this behavior, so am I.

**Pull request merged**
