### PR TITLE
Reorg namespacing

### LINKED ISSUE #3797: Reorganize RPC function namespacing
## Problem

The namespacing of our RPC functions has already become a bit inconsistent, and sometimes misleading.

## Proposed solution

Make the following changes:

| old | new |
|-|-|
| `database_privileges.list_direct`         | `databases.privileges.list_direct` |
| `database_privileges.replace_for_roles`   | `databases.privileges.replace_for_roles` |
| `database_privileges.get_self`            | `databases.get` |
| `database_setup.create_new`               | `databases.setup.create_new` |
| `database_setup.connect_existing`         | `databases.setup.connect_existing` |
| `databases.list`                          | `databases.configured.list`
| `configured_roles.add`                    | `roles.configured.add` |
| `configured_roles.delete`                 | `roles.configured.delete` |
| `configured_roles.list`                   | `roles.configured.list` |
| `configured_roles.set_password`           | `roles.configured.set_password` |
| `schema_privileges.list_direct`           | `schemas.privileges.list_direct` |
| `schema_privileges.replace_for_roles`     | `schemas.privileges.replace_for_roles` |
| `servers.list`                            | `servers.configured.list` |
| `table_privileges.list_direct`            | `tables.privileges.list_direct` |
| `table_privileges.replace_for_roles`      | `tables.privileges.replace_for_roles` |

## Additional context

This arose from much confusion around `database_privileges.get_self`, and noticing that it was getting hard to find some functionality in the current state.

I don't expect this to take more than an hour, but I need to time it when it won't disrupt other work.

### PR DESCRIPTION
**Pull request by mathemancer**
Fixes #3797 

This PR reorganizes and cleans up some of the RPC function code and naming.

**Technical details**

The PR makes the renaming changes in the issue, and also:
- removes an unneeded parameter from `list_db_priv` (no effect on API)
- Modifies the response a bit from `databases.get` (previously `database_privileges.get_self` to conform with what one would expect from such a function. The information is a superset of what was previously returned. 

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the `develop` branch of the repository
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [X] I added tests for the changes I made (if applicable).
- [X] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by mathemancer** [comment]
@Anish9901 Please go through this one a bit carefully, since there were so many renamings.

@pavish This is ready to wire up with the front end.

**Comment by mathemancer** [comment]
@Anish9901 This is ready for backend review, but I'm marking it as 'draft' since @pavish plans to make the front end changes in this same PR.

**Comment by pavish** [comment]
I've wired up the frontend with the changes.

**Review by Anish9901 — APPROVED** [review]
LGTM!

**Pull request merged**
