### PR TITLE
Refactor CellSelection data structure and store

### LINKED ISSUE #1732: Change the data structure to store selections in the selection store
## Problem
The current structure is only capable to store the selected cells. 
`selectedCells: WritableSet<string>;`
This is not usable when the table has no rows hence no cells but the user should still be able to select columns and edit their properties as mentioned in #1684

## The rationale behind current implementation
The current implementation is based on the fact that when a cell is selected, a row and a column are also selected by default. Row selection can be described as selecting all the cells in a particular row. 
Column selection can be described as selecting all the cells in a particular column. 

## Proposed solution

@pavish [proposed](https://github.com/centerofci/mathesar/issues/1684#issuecomment-1256145741) the following design:

> The selection store to utilize a different structure instead of just the identifier string array, something like:
> 
> ```ts
> {
>    type: 'cell' | 'column' | 'row',
>    identifiers: string[],
> }
> ```
> 
> The identifiers here would depend on the type of selection.

### LINKED ISSUE #1893: Keep records in store while fetching
## Current behavior

- Before fetching records, we clear all the existing records replacing them with dummy records just so that each cell displays a loading skeleton.
- In the Record Selector, we're auto-sizing the column widths based on the content of the cells.
- The combination of the above two strategies produces some funky loading behavior in the Record Selector. While searching, the table gets too narrow because the cells no longer have content. Then when the search is complete, the table gets wide again. This causes the UI to jump around which can be disorienting to users.

## Desired behavior

- Don't wipe the records out until we have already fetched them. Maintain a separation of concerns between the records _data_ and the records _fetch status_.
- We can still display loading skeletons on the cells by reacting to the fetch status.

### LINKED ISSUE #1911: Keyboard fails to move active cell after clicking a column header or row header
## Steps to reproduce

1. Go to a table page.
1. Click on a cell to select it.
1. Press `Up`, `Down`, `Left`, `Right`, `Tab` and `Shift+Tab`.
1. Observe the active cell to move in response to the keyboard. Good.
1. Click on a column header to select all the cells within the column.
1. Press those keyboard keys again.
1. Expect the active cell to move as before.
1. Instead, observe that the active cell does not move in response to the keyboard.

### LINKED ISSUE #2122: Weird cell selection behavior when dragging from cell to header
In the video below, notice how the cell selection changes abruptly when dragging from cells to column/row headers.

https://user-images.githubusercontent.com/42411/208515064-5aec64fb-f0c4-4bdd-ac0f-0a7aae5dcf8b.mp4

I would expect it to work like this:

https://user-images.githubusercontent.com/42411/208515593-814c8448-9f00-4f99-89f1-a271f69388a8.mp4

### LINKED ISSUE #2130: Do not select columns when hovering column headers in a table with no rows
## Steps to reproduce

1. Open the Table Page for a table with no rows.
1. Hover the column headers (without clicking).
1. Expect no changes to the cell/column selection.
1. Observe that columns are selected as you hover.

https://user-images.githubusercontent.com/42411/208681963-f897e982-8514-418d-ab32-f22581dfb55e.mp4

CC @rajatvijay

### LINKED ISSUE #2651: In Firefox, dragging to re-order columns is not possible from empty space in column header
## Steps to reproduce

1. Identify a column which is wide enough to have empty space in the column header to the right of the column name.
1. Click on the column header to select the column.
1. Drag to re-order the column by initiating the drag event over the column name text. Observe that the column can be dragged. Good.
1. Drag to re-order the column by initiating the drag event over the empty space to the right of the column name text. Expect that the column is dragged, as before. Instead, observe that nothing happens.

## Notes

- This issue originally surfaced in a [PR review](https://github.com/centerofci/mathesar/pull/2213#pullrequestreview-1262551150). Search the PR comments for `(9)` to see references to this problem within several comments.

- As @AlekLefebvre [mentioned](https://github.com/centerofci/mathesar/pull/2213#issuecomment-1458546855), this issue may be related to a [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=568313#c16).

### LINKED ISSUE #2845: Cell selection partially broken after selecting columns when table is filtered to be empty
## Steps to reproduce

1. Begin with a table that has some rows in it.
1. In the table inspector, enable the "Column" tab
1. Add a filter condition like `"id" = 0` which filters the table to be empty.
1. Click a column header to select the column. (Also note that, due to #2130, hovering column headers also selects them.)
1. Remove the filter condition, showing all rows.
1. Select cells in various columns of the table. As you select cells, observe the highlighted stated of the column headers. Blue column headers indicate that the _column_ is selected.
1. Expect the selected columns to derived from the selected cells.
1. Instead, observe that the column you selected while the table was empty is now stuck being selected regardless of which cells in the table are selected.
1. If you filter the table to be empty again, you can _change_ this "stuck" column, but you can't remove it.
1. Refreshing the page resets the selection back to its know-good state.

@rajatvijay I want to put this on your radar since it relates to the cell selection code, which you've worked on more than anyone else.

### LINKED ISSUE #3205: Reactivity problem with cell value in Data Explorer table inspector
## Description

In the Data Explorer, the cell value in the table inspector only updates when the cell selection changes. It doesn't update when the data changes.

image

## Steps to reproduce

https://github.com/centerofci/mathesar/assets/42411/200d1f3b-999d-41e2-9b85-0240817ec368

### PR DESCRIPTION
**Pull request by seancolsen**
Fixes #1732
Fixes #2845
Fixes #2130
Fixes #2122
Fixes #3205 via aeae784729b10752f03df40923dbe9a93697c60b
Fixes #1893
Fixes #1911
Fixes #2651

## Overview of the new approach to CellSelection in this PR

_(The following text is written declaratively to describe the **expected direction** of this PR. The full implementation is still pending.)_

1. Each cell gets a unique string id. The id is a serialization of the row id and the column id. The code to serialize and parse these id values is made more robust and performant, and it's moved out of SheetSelection.ts, to a common location.

1. The sheet system (polymorphic across the Table Page and Data Explorer) previously held a `SheetSelection` instance (a [granular store](https://github.com/centerofci/mathesar/blob/develop/mathesar_ui/ARCHITECTURE.md#the-mutable-class-pattern---granular-reactivity)). It now holds a `Writable<Selection>` instance instead (a [coarse store](https://github.com/centerofci/mathesar/blob/develop/mathesar_ui/ARCHITECTURE.md#the-immutable-class-pattern---coarse-reactivity)).

1. A `Selection` instance holds a `Plane` instance and a `Basis` instance &mdash; both of which are new constructs.

    - `Plane` is somewhat like a coordinate system for cells in the sheet. It stores all the row ids and column ids in a data structure which permits performant range lookups of certain rectangles, yielding iterators of cell ids in those rectangles.

    - `Basis` stores all the data about the selection that we need to know for external purposes. This is the source of truth for the selection data; but it also contains redundancies for performance purposes.

        There are three basis types (described more fully within the code comments) which correspond to selection types which are _structurally_ different from one another.
        
        - For the `dataCells` basis type, the source of truth is `cellIds` and `activeCellId`, with `rowIds` and `columnIds` being derived from `cellIds`. This is the same design as before. Also as before, this basis type is still used when selecting all the cells in a range of rows or all the cells in a range of columns.
        
        - The two other basis types `emptyColumns` and `placeholderCell` will rarely be used, but exist to support special functionality when the table has no data rows or has a placeholder row.

        - For each basis type, a utility function constructs the basis from its raw requirements and computes the derived data as necessary. Basis instances are never constructed outside these utility functions.

1. `Selection` has methods to generate transformations of the instance based on different actions the user might perform upon the selection. These methods will allow us to easily build new features like Shift + arrow keys to resize selections.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by seancolsen** [comment]
@pavish and @rajatvijay I know we agreed to use an RFC process to discuss these changes, but I felt that I needed to get my hands dirty before I could really figure out how I wanted to do this, so I started with some code. This PR does not yet _change_ any code &mdash; it only adds new code. My hope is that the scaffolding I've done so far, along with the PR description will suffice in lieu of an RFC. Does this give you a clear enough picture of where I'm headed for us to have a discussion about the direction of this refactor?

**Comment by seancolsen** [comment]
@pavish and I discussed this briefly via chat.

The use case he presents is definitely worth handling, and I don't think it will be too hard to handle.

Basically the sheet would hold a `Plane` instance. When the user paginates (and does other things too), the sheet would generate a new `Plane` instance. Any time the `Plane` instance changes, the selection would be updated via its `forNewPlane` method. Within that method we'll be able to incorporate logic like _"if all the cells within the column are selected, then keep that column selected"_

Pavish said that he approves of the basic approach in this PR and that I can move forward with further implementation.

**Comment by seancolsen** [comment]
@rajatvijay Heads up that I'm going to continue working on this tomorrow when I start my day. Please take a look when you begin your day if you'd still like to have an opportunity to review my approach.

**Comment by rajatvijay** [comment]
@seancolsen & I had a chat about it. The approach outlined here is focused on the stability of the cell selection feature. Regarding perf - the goal is not to improve it but definitely not to make it worse. 

LGTM 🚀

**Comment by seancolsen** [comment]
This PR is finally ready for review!

## Review

@pavish I'd be happy to hop on a call to go over any questions that you come up with if you think that would be helpful.

Since we don't plan to make a release for a while, my suggestion is to try to get this merged soon so that we have a good amount of time with our team using the app to spot regressions.

## QA

There's quite a lot to QA here.

@ghislaineguerin I've assigned this PR to you so that you can do prescriptive QA on it from a user's perspective. This PR makes a bunch of changes to the way that cell selection works. For QA I recommend focusing on these things:

- Application areas to QA:
    - Table page, table widget, data explorer, import preview, record selector. These areas all use the "Sheet" system, which is affected by this refactor.
- Features to QA:
    - Pagination
    - Adding/deleting columns
    - Column reordering via drag/drop
    - Column resizing
    - Drag to select multiple rows
    - Drag to select multiple columns
    - Shift+click (or even Shift+click-and-drag) to select range
    - Inspector tab is being auto-selected in both table page and DE
    - Table page with grouping applied
    - Auto-scrolling to cells based on active cell and selected cells
    - Checkbox cell
    - Copy cells from table and from data explorer
    - Ability to arrow-down into cells within placeholder row, and add data
    - Trying to move into the placeholder row when it doesn't exist (e.g. in table share when no permission to add record)
    - Selecting cells within an unsaved new row
    - Adding new records via placeholder row
    - Adding new records via New Record button

During QA, try to pay particular attention to the way that different features interact with the different ways that cells can be selected. Test edge cases you can think of. Try to identify any regressions. If you find problems, make sure to test against the latest release to determine if it's a longstanding bug or a regression.

**Review by pavish — APPROVED** [review]
@seancolsen This looks great and the selection behaviour appears quite stable! Thanks for all your hard work on this.

I tested common operations and didn't notice any major issues. I came across one minor regression: The table insector's tabs do not get highlighted when a column or row is selected. I added a commit to fix this: https://github.com/mathesar-foundation/mathesar/pull/3037/commits/5489684eb0fd75535de3c66137324a22b0baccad.

There is a possibility that I may have missed other tiny regressions such as this. I'd like to merge the PR in and handle them if/when we encounter any.

**Pull request merged**
