### PR TITLE
Add demo target to Dockerfile

### LINKED ISSUE #3522: Demo is broken for 0.1.6
## Description

The demo can't be deployed with the current `master` branch (0.1.6)

The reasons are:

- We didn't add the fix to the demo settings in #3499 (just to prod), and
- We have an extra dependency in the demo setup which we need to build in but the current `Dockerfile` doesn't support that.

## Expected behavior

We should be able to demo version 0.1.6 on our demo site.

### PR DESCRIPTION
**Pull request by mathemancer**
Fixes #3522 

This adds a build stage to the Dockerfile for version 0.1.6, and adds a setting to fix the issue #3497 , but in the demo setting.

Edit: Now the default build is `production`, other targets work as expected.

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the `develop` branch of the repository
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by mathemancer** [comment]
@pavish I converted this to draft, since we may want to change the approach.

**Comment by mathemancer** [comment]
It would violate DRY, but couldn't we just base prod and demo off of the `base` in the same way, copy the build from develop into both, etc.? Then if `production` was last in the file, it would be the one produced by default (I think).

**Comment by mathemancer** [comment]
Okay, I reordered things so production should be the default. I'm going to double-check that everything works as expected, and then mark this ready for review.

**Review by pavish — APPROVED** [review]
@mathemancer Looks good to me!

**Pull request merged**
