### PR TITLE
Updates to documentation

### LINKED ISSUE #3428: Update "Connect to an external database server" docs
On `/configuration/connect-to-existing-db/` this docs page needs some general cleanup.

Specifically, we need to remove the reference to `MATHESAR_DATABASES` since that's deprecated now.

### PR DESCRIPTION
**Pull request by kgodey**
Fixes #3428

This PR makes the following changes:
- Minor language updates to the docs homepage.
- Removed the "Connect to an external database server" page entirely, see below.

### Reasoning for page removal
The page (see [live version](https://docs.mathesar.org/configuration/connect-to-existing-db/)) attempted to document two things:

**(1) How to set up a Mathesar internal database if you're connecting to an external DB**

These steps were out of date anyway, since they referred to configuring the DB via environment variables. Also, it is my understanding that we don't need to perform any steps after the new DB connection UI work in 0.1.4 and that we'll create the internal database automatically. So I removed it.

**(2) How to configure Mathesar to point at a database on the host server if you're using Docker**

My first instinct was to move this to the "Optional configurations" section of the Docker compose installation, and I spent some time doing that and making the documentation more concise. Then I realized that
- none of the documentation was about Mathesar, it's all about configuring Postgres and Docker and is probably outside the scope of our docs.
- we only document one way of doing this and present it as "the way", but there seem to be multiple approaches that can be taken to solve the problem of connecting to a Postgres database on a Docker host
- we're presuming usage of our old Docker compose file

It didn't seem like it was worth cleaning up or having this documentation, so I removed it.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kgodey** [comment]
@mathemancer please double check my reasoning here, that's the main thing I'm asking you to review.

@seancolsen also added you as a reviewer in case you wanted to look at the index page changes.

**Review by seancolsen — APPROVED** [review]

**Review by mathemancer — CHANGES_REQUESTED** [review]
I agree with (2), but (1) isn't correct. If you want to use a specific DB server for the internal (Django) DB, you still set that up using environment variables. This section should perhaps be clarified, but it shouldn't be removed.

**Comment by seancolsen** [comment]
@kgodey I think this PR should target the `0.1.5` branch now, right?

**Review by mathemancer — APPROVED** [review]
LGTM.

**Pull request merged**
